//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from COOLgrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using CmpProject;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="COOLgrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return Type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]

public interface ICOOLgrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="COOLgrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] COOLgrammarParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="COOLgrammarParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass([NotNull] COOLgrammarParser.ClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>method</c>
	/// labeled alternative in <see cref="COOLgrammarParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod([NotNull] COOLgrammarParser.MethodContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>attribute</c>
	/// labeled alternative in <see cref="COOLgrammarParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] COOLgrammarParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="COOLgrammarParser.formal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal([NotNull] COOLgrammarParser.FormalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arith</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArith([NotNull] COOLgrammarParser.ArithContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dispatch</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDispatch([NotNull] COOLgrammarParser.DispatchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>integerExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerExpr([NotNull] COOLgrammarParser.IntegerExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>inParenthesisExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInParenthesisExpr([NotNull] COOLgrammarParser.InParenthesisExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>condExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondExpr([NotNull] COOLgrammarParser.CondExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>letExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetExpr([NotNull] COOLgrammarParser.LetExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpr([NotNull] COOLgrammarParser.StringExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compaExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompaExpr([NotNull] COOLgrammarParser.CompaExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpr([NotNull] COOLgrammarParser.NotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>whileExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileExpr([NotNull] COOLgrammarParser.WhileExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>negExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegExpr([NotNull] COOLgrammarParser.NegExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>isvoidExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsvoidExpr([NotNull] COOLgrammarParser.IsvoidExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockExpr([NotNull] COOLgrammarParser.BlockExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseExpr([NotNull] COOLgrammarParser.CaseExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boolExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolExpr([NotNull] COOLgrammarParser.BoolExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>selfDispatch</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelfDispatch([NotNull] COOLgrammarParser.SelfDispatchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assignExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignExpr([NotNull] COOLgrammarParser.AssignExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>newTypeExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewTypeExpr([NotNull] COOLgrammarParser.NewTypeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>idExpr</c>
	/// labeled alternative in <see cref="COOLgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdExpr([NotNull] COOLgrammarParser.IdExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>letDecl</c>
	/// labeled alternative in <see cref="COOLgrammarParser.letRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetDecl([NotNull] COOLgrammarParser.LetDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>letBody</c>
	/// labeled alternative in <see cref="COOLgrammarParser.letRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetBody([NotNull] COOLgrammarParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="COOLgrammarParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] COOLgrammarParser.ParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="COOLgrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] COOLgrammarParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="COOLgrammarParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBranch([NotNull] COOLgrammarParser.BranchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="COOLgrammarParser.expr_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_list([NotNull] COOLgrammarParser.Expr_listContext context);
}
